controller_list:
  - name: fake_fanuc_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
initial:  # Define initial robot poses.
  - group: fanuc
    pose: home_position